document.querySelectorAll(".tab").forEach(t=>t.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));t.classList.add("active");document.querySelectorAll("form").forEach(f=>f.classList.add("hidden"));document.getElementById(t.dataset.target)?.classList.remove("hidden");}));

const sb=window.supabaseClient||null;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));

document.getElementById("customer")?.addEventListener("submit",async e=>{e.preventDefault();const s=document.getElementById("customerStatus"),email=document.getElementById("customerEmail")?.value.trim(),password=document.getElementById("customerPassword")?.value;if(!sb){s.textContent="Secure login is not connected. Please refresh the page.";return;}if(!email||!password){s.textContent="Please enter your email and password.";return;}s.textContent="Signing in…";const {data,error}=await sb.auth.signInWithPassword({email,password});if(error){s.textContent=error.message;return;}if(!data?.user){s.textContent="Login did not return a user. Please try again.";return;}location.href="dashboard.html";});
document.getElementById("customerSignup")?.addEventListener("click",async e=>{e.preventDefault();const s=document.getElementById("customerStatus"),email=document.getElementById("customerEmail")?.value.trim(),password=document.getElementById("customerPassword")?.value;if(!sb){s.textContent="Secure signup is not connected. Please refresh the page.";return;}if(!email||!password){s.textContent="Enter an email and password first.";return;}if(password.length<6){s.textContent="Password must be at least 6 characters.";return;}s.textContent="Creating your account…";const {data,error}=await sb.auth.signUp({email,password,options:{data:{full_name:email.split("@")[0]},emailRedirectTo:window.location.origin+window.location.pathname}});if(error){s.textContent=error.message;return;}if(data?.session){s.textContent="Account created successfully. Opening your dashboard…";location.href="dashboard.html";return;}s.textContent="Account created. Please check your email and click the confirmation link before logging in.";});
document.getElementById("admin")?.addEventListener("submit",async e=>{e.preventDefault();const s=document.getElementById("adminStatus");if(!sb){s.textContent="Connect the Supabase project first.";return;}const {error}=await sb.auth.signInWithPassword({email:adminEmailLogin.value.trim(),password:adminPassword.value});if(error){s.textContent=error.message;return;}const {data:u}=await sb.auth.getUser();const {data:p}=await sb.from("profiles").select("role").eq("id",u.user.id).single();if(p?.role!=="admin"){await sb.auth.signOut();s.textContent="This account is not authorized as an administrator.";return;}location.href="admin.html";});

async function requireAdmin(){if(!sb){location.href="login.html";return null;}const {data:{user}}=await sb.auth.getUser();if(!user){location.href="login.html";return null;}const {data:profile}=await sb.from("profiles").select("id,full_name,email,phone,role").eq("id",user.id).single();if(!profile||profile.role!=="admin"){await sb.auth.signOut();location.href="login.html";return null;}return {user,profile};}

const adminSections=document.querySelectorAll(".admin-section");
const adminNav=document.querySelectorAll(".admin-nav");
function openAdminSection(name){adminSections.forEach(s=>s.classList.toggle("active",s.id===name));adminNav.forEach(n=>n.classList.toggle("active",n.dataset.section===name));history.replaceState(null,"","#"+name);loadAdminData(name);}
adminNav.forEach(n=>n.addEventListener("click",()=>openAdminSection(n.dataset.section)));
document.querySelectorAll("[data-open]").forEach(b=>b.addEventListener("click",()=>openAdminSection(b.dataset.open)));

async function loadAdminData(section){if(!adminSections.length)return;const a=await requireAdmin();if(!a)return;
if(section==="overview"){const [{count:c},{count:r},{count:p},{count:m}]=await Promise.all([sb.from("profiles").select("*",{count:"exact",head:true}).eq("role","customer"),sb.from("readings").select("*",{count:"exact",head:true}),sb.from("appointments").select("*",{count:"exact",head:true}).eq("status","pending"),sb.from("messages").select("*",{count:"exact",head:true})]);const n=document.querySelectorAll(".admin-stats b");if(n.length){n[0].textContent=c??0;n[1].textContent=r??0;n[2].textContent=p??0;n[3].textContent=m??0;}}
if(section==="customers")await loadCustomers();if(section==="readings")await loadReadings();if(section==="appointments")await loadAppointments();if(section==="messages")await loadMessages();}

async function loadCustomers(){const b=document.querySelector("#customers tbody");if(!b)return;const {data,error}=await sb.from("profiles").select("full_name,email,phone,created_at").eq("role","customer").order("created_at",{ascending:false});if(error){b.innerHTML="<tr><td colspan='4'>"+esc(error.message)+"</td></tr>";return;}b.innerHTML=(data||[]).map(x=>"<tr><td>"+esc(x.full_name)+"</td><td>"+esc(x.email||x.phone||"—")+"</td><td><span class='status active-status'>Active</span></td><td>"+new Date(x.created_at).toLocaleDateString()+"</td></tr>").join("")||"<tr><td colspan='4'>No customers yet.</td></tr>";}
async function loadReadings(){const b=document.querySelector("#readings .reading-list");if(!b)return;const {data,error}=await sb.from("readings").select("title,service,status,created_at,profiles(full_name)").order("created_at",{ascending:false});if(error){b.innerHTML="<article class='admin-card'>"+esc(error.message)+"</article>";return;}b.innerHTML=(data||[]).map(x=>"<article class='admin-card reading-row'><div><strong>"+esc(x.title)+"</strong><small>"+esc(x.profiles?.full_name||"Customer")+" • "+new Date(x.created_at).toLocaleDateString()+"</small></div><span class='status pending-status'>"+esc(x.status)+"</span></article>").join("")||"<article class='admin-card'>No readings yet.</article>";}
async function loadAppointments(){const b=document.getElementById("appointmentsBody");if(!b)return;const {data,error}=await sb.from("appointments").select("service,appointment_date,appointment_time,status,profiles(full_name)").order("appointment_date",{ascending:true}).order("appointment_time",{ascending:true});if(error){b.innerHTML="<tr><td colspan=\"5\">"+esc(error.message)+"</td></tr>";return;}b.innerHTML=(data||[]).map(x=>"<tr><td>"+esc(x.profiles?.full_name||"Customer")+"</td><td>"+esc(x.service)+"</td><td>"+esc(x.appointment_date)+"</td><td>"+esc(String(x.appointment_time).slice(0,5))+"</td><td><span class=\"status "+(x.status==="completed"?"active-status":"pending-status")+"\">"+esc(x.status)+"</span></td></tr>").join("")||"<tr><td colspan=\"5\">No appointments yet.</td></tr>";}
async function loadMessages(){const b=document.getElementById("messageHistory");if(!b)return;const {data,error}=await sb.from("messages").select("channel,message,status,created_at,profiles(full_name,email)").order("created_at",{ascending:false}).limit(50);if(error){b.textContent=error.message;return;}b.innerHTML=(data||[]).map(x=>"<div class='history-item'><strong>"+esc(x.channel)+"</strong><span>"+esc(x.profiles?.full_name||x.profiles?.email||"Customer")+"</span><small>"+esc(x.message)+" • "+new Date(x.created_at).toLocaleString()+"</small></div>").join("")||"<p class='muted'>No messages yet.</p>";}

document.getElementById("sendMessage")?.addEventListener("click",async()=>{const r=document.getElementById("adminRecipient")?.value.trim(),ch=document.getElementById("adminChannel")?.value.toLowerCase(),msg=document.getElementById("adminMessage")?.value.trim(),s=document.getElementById("messageStatus");if(!r||!msg){s.textContent="Enter a customer contact and message.";return;}const a=await requireAdmin();if(!a)return;const {data:c}=await sb.from("profiles").select("id").or("email.eq."+r+",phone.eq."+r).eq("role","customer").limit(1).maybeSingle();if(!c){s.textContent="Customer not found. Register the customer first.";return;}const {error}=await sb.from("messages").insert({customer_id:c.id,sender_id:a.user.id,channel:ch,message:msg,status:"queued"});s.textContent=error?error.message:"Message recorded. External Email/SMS/WhatsApp delivery requires a provider/Edge Function.";if(!error){document.getElementById("adminMessage").value="";await loadMessages();}});

document.getElementById("adminLogout")?.addEventListener("click",async()=>{if(sb)await sb.auth.signOut();location.href="login.html";});
if(adminSections.length){const initial=location.hash.slice(1);openAdminSection([...adminSections].some(s=>s.id===initial)?initial:"overview");}

document.getElementById("saveSettings")?.addEventListener("click",()=>{const s=document.getElementById("settingsStatus");if(s)s.textContent="Authentication and database security are managed by Supabase.";});

const READY_WELCOME="Welcome to our channel, know your hidden secrets and about future with clarity.";
const AI_FALLBACK="Thank you for your question. Our AI Astrology Guide can provide an introductory interpretation, while a detailed personal reading should be prepared from your birth details and consultation information.";
function showAiAnswer(a){const b=document.getElementById("aiWelcome");if(b)b.textContent=a;}
document.getElementById("askAi")?.addEventListener("click",()=>showAiAnswer("Welcome back. "+READY_WELCOME));
document.getElementById("sendAi")?.addEventListener("click",async()=>{const i=document.getElementById("aiQuestion"),q=i?.value.trim(),b=document.getElementById("sendAi");if(!q)return;if(!sb){showAiAnswer("AI service is not connected. Please refresh and try again.");return;}b.disabled=true;b.textContent="Thinking...";showAiAnswer("AI Guide is preparing your answer...");try{const {data:{session}}=await sb.auth.getSession();if(!session){showAiAnswer("Please log in again before asking a question.");return;}const {data,error}=await sb.functions.invoke("generate-reading",{body:{question:q}});if(error||!data?.success)throw new Error(data?.error||error?.message||"The AI Guide could not answer right now.");showAiAnswer(data.answer);i.value="";}catch(err){showAiAnswer("AI Guide: "+(err.message||"Please try again."));}finally{b.disabled=false;b.textContent="Send";}});
document.getElementById("aiQuestion")?.addEventListener("keydown",e=>{if(e.key==="Enter")document.getElementById("sendAi")?.click();});

if(document.querySelector(".dashboard-content")&&sb){(async()=>{const {data:{user}}=await sb.auth.getUser();if(!user){location.href="login.html";return;}const {data:p}=await sb.from("profiles").select("full_name,email,phone,role").eq("id",user.id).single();if(!p||p.role!=="customer"){await sb.auth.signOut();location.href="login.html";return;}const [{count:rc},{count:mc},{count:ac}]=await Promise.all([sb.from("readings").select("*",{count:"exact",head:true}).eq("customer_id",user.id),sb.from("messages").select("*",{count:"exact",head:true}).eq("customer_id",user.id),sb.from("appointments").select("*",{count:"exact",head:true}).eq("customer_id",user.id).eq("status","pending")]);const n=document.querySelectorAll(".dashboard-content .stats b");if(n.length){n[0].textContent=rc??0;n[1].textContent=mc??0;n[2].textContent=ac??0;}})();}
